<?php

/**
 * Implements hook_preprocess_HOOK().
 */
function dug_admin_preprocess_node(&$vars) {
  /** @var \Drupal\node\Entity\Node $node */
  $node = $vars['node'];

  // Contextual links overlay the actions button on a paragraphs field form in
  // "preview" mode. Disable contextual links for nodes of type section_teaser
  // when displayed in "teaser" view mode (which should be exclusive to the
  // paragraphs preview).
  if ($node->getType() === 'section_teaser' && $vars['view_mode'] === 'teaser') {
    $classes = &$vars['attributes']['class'];
    if ($classes && ($contextual = array_search('contextual-region', $classes)) !== FALSE) {
      unset($classes[$contextual]);
    }
  }
}

/**
 * Implement hook_node_presave().
 *
 * @param \Drupal\node\NodeInterface $node
 */
function dug_admin_node_presave(\Drupal\node\NodeInterface $node) {
  if ($node->bundle() == 'talk' && !$node->get('field_done')->isEmpty()) {
    $node->field_done->value = (int) $node->get('field_done')->value;
  }
}
