<?php

use Drupal\migrate\Entity\MigrationInterface;
use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Row;

/**
 * Implements migrate_prepare_row().
 *
 * @param \Drupal\migrate\Row $row
 * @param \Drupal\migrate\Plugin\MigrateSourceInterface $source
 * @param \Drupal\migrate\Entity\MigrationInterface $migration
 */
function dug_migrate_migrate_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  $migration_prefix = 'd6_node__';
  if (strpos($migration->id(), $migration_prefix) !== FALSE) {
    $rows = $source->getDatabase()->query('SELECT td.tid, td.vid  FROM {term_node} tn INNER JOIN {term_data} td ON tn.tid = td.tid WHERE tn.vid = :vid', [':vid' => $row->getSourceProperty('vid')])->fetchAll();
    $terms = [];
    foreach ($rows as $term) {
      $terms[$term->vid][] = $term->tid;
    }
    $row->setSourceProperty('taxonomy_terms', $terms);
  }
}
